using Unity.Netcode;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using BomberTeen;

/// <summary>
/// Script responsible for managing each fire "block" generated by the bomb.
/// Synchronizes via RPC which piece of the fire texture (start, middle, or end) will be rendered
/// on all screens, rotating the image according to the original vector.
/// </summary>
public class Explosion : NetworkBehaviour
{
    [Header("Explosion Animations")]
    public AnimatedSpriteRenderer start;
    public AnimatedSpriteRenderer middle;
    public AnimatedSpriteRenderer end;

    [Tooltip("Time in seconds before the explosion tile despawns.")]
    public float duration = 1.0f;

    private readonly NetworkVariable<Unity.Collections.FixedString32Bytes> networkRendererType = new NetworkVariable<Unity.Collections.FixedString32Bytes>(
        default,
        NetworkVariableReadPermission.Everyone,
        NetworkVariableWritePermission.Server
    );

    private readonly NetworkVariable<Vector2> networkDirection = new NetworkVariable<Vector2>(
        default,
        NetworkVariableReadPermission.Everyone,
        NetworkVariableWritePermission.Server
    );

    private void Start()
    {
        if (AudioManager.instance != null)
        {
            AudioManager.instance.PlaySFX(Constants.Audio.Explosion);
        }
    }

    public override void OnNetworkSpawn()
    {
        networkRendererType.OnValueChanged += HandleRendererChanged;
        networkDirection.OnValueChanged += HandleDirectionChanged;

        if (IsServer)
        {
            StartCoroutine(ServerDespawnRoutine());
        }
        else
        {
            if (!networkRendererType.Value.IsEmpty)
            {
                ApplyActiveRenderer(networkRendererType.Value.ToString());
            }
            if (networkDirection.Value != Vector2.zero)
            {
                ApplyDirection(networkDirection.Value);
            }
        }
    }

    public override void OnNetworkDespawn()
    {
        networkRendererType.OnValueChanged -= HandleRendererChanged;
        networkDirection.OnValueChanged -= HandleDirectionChanged;
    }

    private void HandleRendererChanged(Unity.Collections.FixedString32Bytes oldVal, Unity.Collections.FixedString32Bytes newVal)
    {
        if (!newVal.IsEmpty)
        {
            ApplyActiveRenderer(newVal.ToString());
        }
    }

    private void HandleDirectionChanged(Vector2 oldVal, Vector2 newVal)
    {
        if (newVal != Vector2.zero)
        {
            ApplyDirection(newVal);
        }
    }

    private IEnumerator ServerDespawnRoutine()
    {
        yield return new WaitForSeconds(duration);
        if (NetworkObject != null && NetworkObject.IsSpawned)
        {
            NetworkObject.Despawn(true);
        }
    }

    /// <summary> Visually activates only the matching piece of the explosion (start, middle, or end). </summary>
    public void ApplyActiveRenderer(string renderer)
    {
        bool isStart = renderer == Constants.Animations.ExplosionStart;
        bool isMiddle = renderer == Constants.Animations.ExplosionMiddle;
        bool isEnd = renderer == Constants.Animations.ExplosionEnd;

        if (start != null)
        {
            start.enabled = isStart;
            if (start.TryGetComponent<SpriteRenderer>(out var sr))
            {
                sr.enabled = isStart;
            }
        }
        if (middle != null)
        {
            middle.enabled = isMiddle;
            if (middle.TryGetComponent<SpriteRenderer>(out var sr))
            {
                sr.enabled = isMiddle;
            }
        }
        if (end != null)
        {
            end.enabled = isEnd;
            if (end.TryGetComponent<SpriteRenderer>(out var sr))
            {
                sr.enabled = isEnd;
            }
        }
    }

    public void ApplyDirection(Vector2 direction)
    {
        if (direction == Vector2.zero) return;
        float angle = Mathf.Atan2(direction.y, direction.x);
        transform.rotation = Quaternion.AngleAxis(angle * Mathf.Rad2Deg, Vector3.forward);
    }

    /// <summary> RPC called by Bomb to visually activate only one of the three fire pieces. </summary>
    [Rpc(SendTo.ClientsAndHost)]
    public void SetActiveRendererRpc(string renderer)
    {
        if (IsServer)
        {
            networkRendererType.Value = renderer;
        }
        ApplyActiveRenderer(renderer);
    }

    /// <summary> 
    /// RPC that receives the direction and converts it to an angle in Degrees using Arc-Tangent (Atan2), 
    /// rotating the fire art to the correct Z axis. 
    /// </summary>
    [Rpc(SendTo.ClientsAndHost)]
    public void SetDirectionRpc(Vector2 direction)
    {
        if (IsServer)
        {
            networkDirection.Value = direction;
        }
        ApplyDirection(direction);
    }
}
