using Unity.Netcode;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using BomberTeen;

/// <summary>
/// Script responsible for managing each fire "block" generated by the bomb.
/// Synchronizes via RPC which piece of the fire texture (start, middle, or end) will be rendered
/// on all screens, rotating the image according to the original vector.
/// </summary>
public class Explosion : NetworkBehaviour
{
    [Header("Explosion Animations")]
    public AnimatedSpriteRenderer start;
    public AnimatedSpriteRenderer middle;
    public AnimatedSpriteRenderer end;

    /// <summary> RPC called by BombController to visually activate only one of the three fire pieces. </summary>
    [Rpc(SendTo.ClientsAndHost)]
    public void SetActiveRendererRpc(string renderer)
    {
        start.enabled = renderer == Constants.Animations.ExplosionStart;
        middle.enabled = renderer == Constants.Animations.ExplosionMiddle;
        end.enabled = renderer == Constants.Animations.ExplosionEnd;
    }

    /// <summary> 
    /// RPC that receives the direction and converts it to an angle in Degrees using Arc-Tangent (Atan2), 
    /// rotating the fire art to the correct Z axis. 
    /// </summary>
    [Rpc(SendTo.ClientsAndHost)]
    public void SetDirectionRpc(Vector2 direction)
    {
        float angle = Mathf.Atan2(direction.y, direction.x);
        transform.rotation = Quaternion.AngleAxis(angle * Mathf.Rad2Deg, Vector3.forward);
    }

    /// <summary> 
    /// RPC that deletes the fire block from the map after the smoke clears.
    /// (Uses Unity's default Destroy function because the explosion was instantiated without specific network ownership and needs to disappear universally)
    /// </summary>
    [Rpc(SendTo.ClientsAndHost)]
    public void DestroyAfterRpc(float seconds)
    {
        Destroy(gameObject, seconds);
    }
}
